version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cabin_system_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cabin_system
      POSTGRES_USER: cabin_user
      POSTGRES_PASSWORD: cabin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cabin_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cabin_system_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cabinsystem.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cabin_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cabin_network:
    driver: bridge 